-- ============================================================
--  V1: initial schema
--  Matches the schema Hibernate generated (ddl-auto=update) before Flyway was introduced,
--  so databases created that way can be baselined at V2 (see application.properties).
--  Written in SQL that runs on both PostgreSQL and H2 (tests).
-- ============================================================

CREATE TABLE certifications (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credential_url VARCHAR(255),
    date           VARCHAR(255),
    issuer         VARCHAR(255) NOT NULL,
    name           VARCHAR(255) NOT NULL
);

CREATE TABLE educations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    degree      VARCHAR(255) NOT NULL,
    end_date    VARCHAR(255),
    field       VARCHAR(255) NOT NULL,
    institution VARCHAR(255) NOT NULL,
    location    VARCHAR(255),
    start_date  VARCHAR(255)
);

CREATE TABLE experiences (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company    VARCHAR(255) NOT NULL,
    end_date   VARCHAR(255),
    location   VARCHAR(255),
    role       VARCHAR(255) NOT NULL,
    start_date VARCHAR(255) NOT NULL
);

CREATE TABLE experience_responsibilities (
    experience_id  BIGINT NOT NULL,
    responsibility VARCHAR(255),
    CONSTRAINT fk_experience_responsibilities_experience
        FOREIGN KEY (experience_id) REFERENCES experiences (id)
);

CREATE TABLE history_entries (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category    VARCHAR(255) NOT NULL,
    date        VARCHAR(255) NOT NULL,
    description TEXT,
    title       VARCHAR(255) NOT NULL
);

CREATE TABLE projects (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category    VARCHAR(255) NOT NULL,
    description TEXT,
    featured    BOOLEAN NOT NULL,
    github_url  VARCHAR(255),
    name        VARCHAR(255) NOT NULL,
    url         VARCHAR(255)
);

CREATE TABLE project_tech_stack (
    project_id BIGINT NOT NULL,
    tech       VARCHAR(255),
    CONSTRAINT fk_project_tech_stack_project
        FOREIGN KEY (project_id) REFERENCES projects (id)
);

CREATE TABLE skills (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(255) NOT NULL
);

CREATE TABLE skill_items (
    skill_id BIGINT NOT NULL,
    item     VARCHAR(255),
    CONSTRAINT fk_skill_items_skill
        FOREIGN KEY (skill_id) REFERENCES skills (id)
);
