-- ============================================================
--  V3: site owner profile (About / Contact / footer), editable in the admin panel
--  One row. Seeded with the text that used to be hard-coded in the frontend.
-- ============================================================

CREATE TABLE profiles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    headline     VARCHAR(255),
    bio          TEXT,
    github_url   VARCHAR(255),
    linkedin_url VARCHAR(255),
    email        VARCHAR(255)
);

INSERT INTO profiles (name, headline, bio, github_url, linkedin_url, email)
VALUES (
    'Vitalii Galkin',
    'Engineer transitioning into Software & Automation',
    'Engineer transitioning into software and automation, with a background in real-world control systems and hands-on experience building ML pipelines, containerised APIs, and workflow automations. Currently completing a Bachelor of Computer Science at the University of London. Based in Auckland, NZ.',
    'https://github.com/v-galkin',
    'https://www.linkedin.com/in/vitalii-galkin-b9920016b',
    NULL
);
